modLoader="javafml"
loaderVersion="[47,)"
license="free to copy"

[[mods]]
modId="bloodra1n"
version="0.0.8"
displayName="Bloodra1n"
displayURL="https://modrinth.com/mod/bloodra1n"
logoFile="logo.png"
credits="Oskarcatnap"
authors="Oskarcatnap"
description="Bloodra1n is just this mod name"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bloodra1n]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration